export const LISTINGS = [
  {
    id: "a1",
    type: "avti",
    title: "Volkswagen Golf 2.0 TDI",
    price: 11900,
    location: "Ljubljana",
    year: 2017,
    km: 158000,
    fuel: "Diesel",
    make: "Volkswagen",
    model: "Golf",
    condition: "Rabljeno",
  },
  {
    id: "a2",
    type: "avti",
    title: "Škoda Octavia 1.6 TDI",
    price: 8900,
    location: "Celje",
    year: 2016,
    km: 210000,
    fuel: "Diesel",
    make: "Škoda",
    model: "Octavia",
    condition: "Rabljeno",
  },
  {
    id: "d1",
    type: "deli",
    title: "Platišča 18'' (5x112)",
    price: 450,
    location: "Kranj",
    make: "Volkswagen",
    model: "",
    condition: "Rabljeno",
  },
];